newplanin/home/urls.py
from django.urls import path 
from . import views


app_name = "home"

urlpatterns = [
    path('', views.load_project_lists, name = "home"),
    path('create-project/', views.create_project, name="create"),
    path('edit-project/<str:pid>/',views.edit_project, name="edit"),
    path('delete-project/<str:pid>/',views.delete_project, name="delete")
    # path('invite/<int:pid>/<str:user_email>',views.invite_users, name="invite_users")
]

newplanin/newplanin/urls.py
import re
from django.contrib import admin
from django.urls import path , include
from django.shortcuts import redirect
from django.urls import reverse
from datetime import datetime
from django.http import JsonResponse
from login import views
# def google_login(request) :
#     return redirect(reverse(login:))
def social_login_cancel(request) :
    return redirect(reverse("boot:login") + "?error=cancelled")

def social_login_error(request) :
    return redirect(reverse("boot:login") + "?error=error")

# def google_login(reqeust) :
#     return redirect(reverse('https://accounts.google.com/o/oauth2/auth/oauthchooseaccount')+"?client_id=")


def test_timezone(request):
    print(request.GET.get("time"))
    print(datetime.now())
    return JsonResponse({
        "now": str(datetime.now())
    })


urlpatterns = [
    path("test-time/", test_timezone),
    # path("accounts/google/login/",google_login),
    path("accounts/social/login/cancelled",social_login_cancel),
    path("accounts/social/login/error", social_login_error),
    path('accounts/',include('allauth.urls')),

    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('',views.login),
    path('home/', include('home.urls')),
    path('calendar/',include('master_calendar.urls')),
    

]

newplanin/home/models.py
from django.db import models

# Create your models here.

newplanin/home/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse, HttpResponseRedirect
from home.create import *
from django.urls import reverse
from master_calendar.models import *
from home.email import sendEmailToUser


# Create your views here.
def load_project_lists(request) :
    if request.user.is_authenticated:
        if request.method == 'GET' :
            user = User.objects.get(id=request.user.id)
            user_projects = Project.objects.filter(creator=user)
            context = {
                "user_projects" : user_projects
            }
            return render(request, 'home/home.html',context)
        if request.method == 'POST' :
            return HttpResponseRedirect(reverse("home:create"))
    else :
        return HttpResponseRedirect(reverse("login:login"))

def create_project(request) :
    if request.method == 'GET' : 
        return render (request,'home/create-project.html' )
    
    if request.method == 'POST' :
        name = request.POST["project-name"]
        creator_id = request.user.id
        start_date = request.POST["project-start-date"]
        end_date = request.POST["project-end-date"]
        new_project = create_new_project(name, creator_id, start_date, end_date)
       
        shared_users_name_email_str= str(request.POST.get("project-shared-user-name-email",False))
        shared_users = parseSharedUserStr(shared_users_name_email_str)
        print(shared_users)

        for shared_user in shared_users :
            name = shared_user.get("name")
            email = shared_user.get("email")
            shared_user_info = track_user_info(name,email)
            add_users_to_project(shared_user_info.id,new_project.id)
            pass_key = shared_user_info.pass_key
            pid = new_project.pid
            sendEmailToUser(pass_key,pid)

        return HttpResponseRedirect(reverse("home:home"))

def parseSharedUserStr(shared_users_name_email_str) :
    users_name_email = shared_users_name_email_str.splitlines()
    shared_user_info = []
    for a_user_name_email in users_name_email:
        if a_user_name_email is None:
            continue
        name_email = a_user_name_email.split("/")
        # name_email ['이진현','rig8696@naver.com']
        dictkey= ["name","email"] 
        user_info = dict(zip(dictkey, name_email)) 
        shared_user_info.append(user_info)
    return shared_user_info

def edit_project(request,pid) :
    a_project = Project.objects.get(pid=pid)
    shared_users = a_project.users.all()
    context = {
        "name" : a_project.name,
        "end_date" : a_project.end_date,
        "start_date" : a_project.start_date,
        "pid" : pid,
        "shared_users" : shared_users
    }
    if request.method == 'GET' :
        return render(request,'home/edit-project.html',context)

    if request.method == 'POST' :
        a_project.name = request.POST["project-name"]
        a_project.end_date = request.POST["project-end-date"]
        a_project.start_date = request.POST["project-start-date"]
        a_project.save()

        shared_users_name_email_str= str(request.POST.get("project-shared-user-name-email",False))
        shared_users = parseSharedUserStr(shared_users_name_email_str)

        for shared_user in shared_users :
            name = shared_user.get("name")
            email = shared_user.get("email")
            pass_key = shared_user.get("pass_key")
            pid = a_project.pid
            new_shared_user = track_user_info(name,email)
            print(new_shared_user)
            pass_key = new_shared_user.pass_key
            pid = a_project.pid
            print(pass_key)
            print(pid)
            sendEmailToUser(pass_key,pid)
            
        return HttpResponseRedirect(reverse("home:home"))


def delete_project(request,pid) :
     if request.method == "POST" :
        a_project = Project.objects.get(pid = pid)
        a_project.delete()
        return HttpResponseRedirect(reverse("home:home"))

# def invite_users(request,pid,user_email) :
#     request.method == 'POST' 

newplanin/home/templates/home/create-project.html
{% extends 'base.html' %}
{% load static %}

{%block title%}project dashboard{% endblock %}
{% block head %}
<script src="{% static 'home/js/create-project.js' %}"></script>
{%endblock%}
{%block body%}
    <form actions = "{% url 'home:create' %}" method = "post" id="create-project" onsubmit="return sendAlertNewProject()">
        {% csrf_token %} 
        <div>     
        <div class = 'project-setting'>
            <h1>포지션 생성하기</h1>
            <p>생성할 포지션 정보를 입력해주세요</p>
        </div>
            <div class="position-container">
            <div>    
                <p>포지션 이름 : </p>
                <input type="text" id="project-name-input" name="project-name"  maxlength="32" placeholder="ex.UXUI면접일"/>
            </div>
            <div>
                <label for="appt">
                <p>인터뷰 진행 기간: </p>
                <input type="date" id="calendar-start-date-input" name="project-start-date"/>
                <span>~</span>
                <input type="date" id="calendar-end-date-input" name="project-end-date"/>
                </label>
            </div>
            <div>
                <p> 면접관 추가하기 </p>
                <p> 이름/이메일 : </p>
                <textarea form="create-project" id="project-shared-user-input" name="project-shared-user-name-email" 
                placeholder="김00/hi@example.comment&#10;이00/test@example.com" style="width:255px;height:70px"></textarea>
            <div>  
        </div>
        <div>
            <p> 아래 버튼을 누르면 면접관들에게 초대 메일이 발송됩니다 </p>
            <input type = "submit" id="project-submit-btn"  value = "면접관 초대하기">
        </div>
        </div>
    </form>
    <!-- Modal content -->
{%endblock%}

newplanin/home/templates/home/edit-project.html
{% extends 'base.html' %}
{% load static %}

{% block title %} project edit {% endblock %}
{% block head%}    
    <script src="{% static 'home/js/create-project.js' %}"></script>
{% endblock %}
{% block body %}
<form actions = "{% url 'home:edit' pid %}" method = "post" id="edit-project" onsubmit="sendAlertEditProject()">
    {% csrf_token %}      
    <div class = 'project-editing-container'>
        <div class="project-setting">
        <h1>포지션 정보 수정하기</h1>
        <p>수정할 포지션 정보를 입력해주세요</p>
        </div>
        <div class = "project-editing">
                <div>    
                    <p>포지션 이름 수정: </p>
                    <input type="text" id="project-name-input" name="project-name"  maxlength="32" placeholder="{{name}}"/>
                </div>
                <div>
                    <label for="appt">
                    <p> 현재 인터뷰 진행 기간 :</p>
                    <p>{{start_date}} ~ {{end_date}}</p>
                    <p>인터뷰 진행 기간 수정하기 : </span>
                    <input type="date" id="calendar-start-date-input" name="project-start-date"  value="{{start_date}}"/>
                    <span>~</span>
                    <h4> </h4>
                    <input type="date" id="calendar-end-date-input" name="project-end-date" value="{{end_date}}"/>
                    </label>
                </div>
                <div>
                    <p> 현재 참여중인 면접관 : </p>
                    <p>
                    {% for shared_user in shared_users %}
                    {{shared_user.name}}, {{shared_user.email}} <br/>
                    {% endfor %}
                    </p>
                    <p> 새로운 면접관 추가하기 </p>
                    <p> 이름/이메일 : </p>
                    <textarea form="edit-project" id="project-shared-user-input" name="project-shared-user-name-email" 
                    placeholder="김00/hi@example.comment&#10;이00/test@example.com" style="width:255px;height:70px"></textarea>  
            </div>
            <div>
                <input type = "submit" id="project-submit-btn"  value = "포지션 정보 수정하기">
            </div>
        </div>
</form>
{% endblock %}

newplanin/home/templates/home/email.html
{% autoescape off %}

안녕하세요! {{ shared_user }}님! 
{{ project_title }} 면접 일정 조정에 초대 되셨습니다.
{{ project_start_date }}에서 {{ project_end_date }}까지
아래의 링크로 접속하여 가능한 일정을 입력해주세요. 
{{ link }}

{% endautoescape %}

        

newplanin/home/templates/home/email_slot.html
{% autoescape off %}

안녕하세요! {{ shared_user }}님! 
{{ project_start_date }}에서 {{ project_end_date }}내에서

{{ project_title }} 면접이 가능한 슬롯을 전달 드립니다. 

{% for slot in slots %}
{{slot}}
{% endslot %}

참여한 면접관들은 아래와 같습니다. 
{% for user in shared_users %}
{{user.name}} , {{user.email}]}

감사합니다
플래닌 드림

{% endautoescape %}

newplanin/home/templates/home/email_slot_unavailable.html
{% autoescape off %}

안녕하세요! {{ shared_user }}님! 
{{ project_start_date }}에서 {{ project_end_date }}내에서

{{ project_title }} 면접이 가능한 슬롯이 없습니다. 

참여한 면접관들은 아래와 같습니다. 
{% for user in shared_users %}
{{user.name}} , {{user.email}]}

감사합니다
플래닌 드림

{% endautoescape %}

newplanin/home/templates/home/home.html
{% extends "base.html"%}
{% load static %}

{% block title %}project list{% endblock %}

{% block body %}
    <h1 class="calendar-title"> {{user.username}}님의 진행중인 포지션 입니다.</h1>
    <div class="project-wrapper">
    {% for project in user_projects %}
        <div class="container-box">
        <p>포지션 이름 : {{project.name}}</p>
        <p>인터뷰 진행 기간 : {{project.start_date}} ~ {{project.end_date}}</p>
        <p>참여 면접관 : 
            {% for shared_user in project.users.all %}</p>
            {{shared_user.name}}, {{shared_user.email}}
    {% endfor %}
            <div class="buttons">
            <button class="edit" type = "submit" onclick="location.href = `{% url 'home:edit' project.pid %}`">수정하기</button>
            <form action="{% url 'home:delete' project.pid %}" method ="post">
                {% csrf_token %}
                <input type = "submit" value = "삭제하기"/>
            </form>
            </div>
        </div>
    {% endfor %}
    </div>
    <div class="make-position">
        <button type = "submit" onclick="location.href = `{% url 'home:create' %}`">포지션 생성하기</button>
    </div>
{%endblock%}