newplanin/home/urls.py
from django.urls import path 
from . import views


app_name = "home"

urlpatterns = [
    path('', views.load_project_lists, name = "home"),
    path('create-project/', views.create_project, name="create"),
    path('edit-project/<str:pid>/',views.edit_project, name="edit"),
    path('delete-project/<str:pid>/',views.delete_project, name="delete")
    # path('invite/<int:pid>/<str:user_email>',views.invite_users, name="invite_users")
]

newplanin/login/urls.py
from django.urls import path 
from . import views


app_name = "login"

urlpatterns = [
    path('', views.login, name ='login'),
    path('logout/', views.logout, name ='logout'),
   
]

newplanin/master_calendar/urls.py
from django.urls import path
from . import views 

app_name = "master_calendar"

urlpatterns = [
    path('<str:pid>/<str:pass_key>/',views.guest_calendar, name ="calendar"),
    path('<str:pid>/<str:pass_key>/save-events/', views.save_events, name="save"),
    path('thankyou/', views.thank_you, name="thankyou"),
]

newplanin/newplanin/urls.py
import re
from django.contrib import admin
from django.urls import path , include
from django.shortcuts import redirect
from django.urls import reverse
from datetime import datetime
from django.http import JsonResponse
from login import views
# def google_login(request) :
#     return redirect(reverse(login:))
def social_login_cancel(request) :
    return redirect(reverse("boot:login") + "?error=cancelled")

def social_login_error(request) :
    return redirect(reverse("boot:login") + "?error=error")

# def google_login(reqeust) :
#     return redirect(reverse('https://accounts.google.com/o/oauth2/auth/oauthchooseaccount')+"?client_id=")


def test_timezone(request):
    print(request.GET.get("time"))
    print(datetime.now())
    return JsonResponse({
        "now": str(datetime.now())
    })


urlpatterns = [
    path("test-time/", test_timezone),
    # path("accounts/google/login/",google_login),
    path("accounts/social/login/cancelled",social_login_cancel),
    path("accounts/social/login/error", social_login_error),
    path('accounts/',include('allauth.urls')),

    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('',views.login),
    path('home/', include('home.urls')),
    path('calendar/',include('master_calendar.urls')),
    

]

newplanin/master_calendar/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser) :
    pass

class UserTrackInfo(models.Model):
    name = models.CharField(max_length=32,null=True, blank=True)
    email = models.CharField(max_length=64,null=True, blank=True)
    pass_key = models.CharField(max_length=32, null=True, blank=True) #랜덤 

class PostingInfo(models.Model):
    has_posted = models.BooleanField(default=False)
    
class Project(models.Model):
    name = models.CharField(max_length=32)
    pid = models.CharField(max_length=64, null=True, blank=True) #랜덤
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="projects_created", null=True, blank=True)
    users = models.ManyToManyField(UserTrackInfo, related_name="projects")
    user_posting_info = models.ManyToManyField(PostingInfo, related_name="project")
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

class Slot(models.Model):
    def copy(self):
        _slot = Slot.create(self.start_timedate, self.end_timedate)
        _slot.name = self.name
        _slot.creator = self.creator
        return _slot

    def create(start, end):
        _slot = Slot()
        _slot.start_timedate = start
        _slot.end_timedate = end
        return _slot

    name = models.CharField(max_length=32)
    creator = models.ForeignKey(UserTrackInfo, on_delete=models.CASCADE, related_name="user_created_slots")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="project_slots")
    start_timedate = models.DateTimeField()
    end_timedate = models.DateTimeField()

newplanin/master_calendar/views.py
from django.forms import NullBooleanField
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse, HttpResponseRedirect
from master_calendar.models import *
from master_calendar.create_models import *
import json
from django.urls import reverse
from datetime import datetime
from master_calendar.logics.manager import *


# Create your views here.

def guest_calendar(request,pid,pass_key):
    #프로젝트의 내용을 담고 있는 링크?
    project = Project.objects.get(pid=pid)
    user = UserTrackInfo.objects.get(pass_key=pass_key)
    shared_users = project.users.all()
    context ={
        "pid":pid,
        "project_name" : project.name, 
        "project_creator" : project.creator,
        "start_date" : project.start_date,
        "end_date" : project.end_date,
        "shared_users": shared_users,
        "user" : user,
        "username" : user.name,
        "pass_key" : pass_key,
    }
    
    if request.method == "GET" :
        print(context.get("start_date"))
        return render(request,'master_calendar/guest_calendar.html',context)

def save_events(request, pid, pass_key) :
    if request.method == "POST" :
        response_body = json.loads(request.body)
        slots = response_body.get("slots")
        slot_model_list = []

        for slot in slots: 
            name = slot.get("name") 
            start_timedate = slot.get("start_timedate")
            end_timedate = slot.get("end_timedate")
            pid = slot.get("pid")
            pass_key= slot.get("pass_key")
            creator = get_object_or_404(UserTrackInfo,pass_key=pass_key)
            slot_model_list.append(create_slot(name, start_timedate,end_timedate, pid,creator.id))

        on_save_slots(pid, slot_model_list)
        return JsonResponse({})

def thank_you(request) :
    return render(request,'master_calendar/thankyou.html')


# def calendar(request):
#     if request.method == 'GET':
#         return render(request,'master_calendar/calendar.html')
#     elif request.method == 'POST':
#         return redirect("/create-project/")

# def load_events(request,pid,pass_key) :
#     # print(request.user)로도 됨?
#     response_body = json.loads(request.body)
#     creator_id = response_body.get("creator_id")
#     creator_events = Slot.objects.filter(creator_id = creator_id)
#     event_list = list(creator_events.values('name','start_timedate','end_timedate','project_id'))
#     return JsonResponse({
#         "events" : event_list
#     })

newplanin/master_calendar/templates/master_calendar/calendar.html
{% load static %}
<html lang='en'>
<head>
  <meta charset='utf-8' />
  <link href="{% static 'master_calendar/css/main.css' %}" rel="stylesheet"/>
  <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet'/>
  <link href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css' rel='stylesheet'/>
  <script src="{% static 'master_calendar/js/main.js' %}"></script>
  <script src="{% static 'master_calendar/js/create_calendar.js' %}"></script>
 
</head>
<body>
{% if user.is_authenticated %}
<div class = "container">
    <a href = "/accounts/logout/">logout</a>
    <div><h1>{{user.username}}님의 공유 캘린더입니다.</h1></div>
</div>
<div class ="master-option-box">
    <!-- adjustable due date -->
    <h3> 캘린더 설정</h3>

    <div class= info-item id = adjustable-date>
      <label for="appt">일정 조정 기간:
        <input type="date" id="calendar-start-date" />
        <span>~</span>
        <input type="date" id="calendar-end-date"/>
        <button id = "calendar-start-end-date" onclick ="setBackgroundTime()"> 설정 </button>
      </label>
    </div>
    <!-- business hour on off switch -->
    <div id = explanation> Working Hours (9am - 9pm)
      <label class="switch">
          <input type="checkbox" id="businessHours" onclick="buisnessHoursOnOff()"/>
          <span class="slider round"></span>
      </label>
   </div>
</div>
    <!-- shared calendar -->
    <label for = "showcalendar"> 
        <input type = "checkbox" id="my-event-checkbox" name="my-evnet"  onclick="showEventof({{user.id}})"> 내 일정
        <input type = "checkbox" id="common-event-checkbox" name="common-event" onclick="showCommonEvent(3)" > 추출 일정 (지금은 id 3 user)
    </label>


<div id="calendar-container">
  <div id="calendar"></div>
</div>
<!-- <button onclick="promptBasedEvent()">추가하기</button>  -->
<button id = "data-load" onclick="sendAllEvents({{user.id}})">제출하기</button>
<br/>
<button type="button" onclick="location.href = '/calendar/create-project/';">공유할 면접관 추가하기</button>

{% else %}
<p>로그인하세요</p>
<a href = "/accounts/google/login/">login</a>

{% endif %}
</body>
</html>

newplanin/master_calendar/templates/master_calendar/email.html
{% autoescape off %}

안녕하세요! {{ user }}님! 

{{ project_title }} 면접이 가능한 슬롯을 전달 드립니다. 

{{ content }}

감사합니다
플래닌 드림

{% endautoescape %}

newplanin/master_calendar/templates/master_calendar/guest-calendar.html
{% load static %}
<html lang='en'>
<head>
  <meta charset='utf-8' />
  <link href="{% static 'master_calendar/css/main.css' %}" rel="stylesheet"/>
  <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet'/>
  <link href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css' rel='stylesheet'/>
  <script src="{% static 'master_calendar/js/main.js' %}"></script>
  <script src="{% static 'master_calendar/js/create_calendar.js' %}"></script>
 
</head>
<body>
{% if user.is_authenticated %}
<div class = "info-box">
    <a href = "x/accounts/logout/">logout</a>
    <div><h1>{{user.username}}님의 공유 캘린더입니다.</h1></div>
</div>
<!-- <div class ="master-option-box">
    <h3> 캘린더 설정</h3>
    <div id = adjustable-date>
      <label for="appt">일정 조정 기간:
        <input type="date" id="calendar-start-date" />
        <span>~</span>
        <input type="date" id="calendar-end-date"/>
        <button id = "calendar-start-end-date" onclick ="setBackgroundTime()"> 설정 </button>
      </label>
    </div>
    <div id = explanation> Working Hours (9am - 9pm)
      <label class="switch">
          <input type="checkbox" id="businessHours" onclick="buisnessHoursOnOff()"/>
          <span class="slider round"></span>
      </label>
   </div>
</div> -->
    <!-- shared calendar -->
    <label for = "showcalendar"> 
        <input type = "checkbox" id="my-event-checkbox" name="my-evnet"  onclick="showEventof({{user.id}})"> 내 일정
        <input type = "checkbox" id="common-event-checkbox" name="common-event" onclick="showCommonEvent(3)" > 추출 일정 (지금은 id 3 user)
    </label>


<div id="calendar-container">
  <div id="calendar"></div>
</div>
<!-- <button onclick="promptBasedEvent()">추가하기</button>  -->
<button id = "data-load" onclick="sendAllEvents({{user.id}})">제출하기</button>
<br/>
<!-- <input type = "submit" value = "프로젝트 공유하기"></input> -->

{% else %}
<p>로그인하세요</p>
<a href = "/accounts/google/login/">login</a>

{% endif %}
</body>
</html>

newplanin/master_calendar/templates/master_calendar/guest_calendar.html
{% load static %}
<html lang='en'>
<head>

  <meta charset='utf-8' />
  <link herf="{% static 'master_calendar/css/calendar.css' %}" rel="stylesheet"/>
  <link href="{% static 'master_calendar/css/main.css' %}" rel="stylesheet"/>
  <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet'/>
  <link href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css' rel='stylesheet'/>
  <script src="{% static 'master_calendar/js/main.js' %}"></script>
  <script src="{% static 'master_calendar/js/create_calendar.js' %}"></script>

</head>
<body>

<div id="info-box">
  <h1>{{username}}님의 공유 캘린더입니다.</h1>
  <div class ="position-info-item">
      <h4>포지션 정보</h4>
      <p>포지션 이름 : {{project_name}}<br/>
      인터뷰 참여 면접관 :
      {% for user in shared_users %}
      {{user.name}} , {{user.email}}<br/>
        <!-- 가능한 슬롯 보기 : <input type = "checkbox" id="my-event-checkbox" name="my-evnet"  onclick="showEventof({{user.id}})"> -->
      {% endfor %}
  
      인터뷰 진행 기간 :<br/>
      {{start_date}} ~ {{end_date}} <br/>
      <!-- <label for = "showcalendar"> 
        <input type = "checkbox" id="my-event-checkbox" name="my-evnet"  onclick="showEventof({{user.id}})"> 내 일정
        <input type = "checkbox" id="common-event-checkbox" name="common-event" onclick="showCommonEvent(3)" > 추출 일정 (지금은 id 3 user)
      </label> -->
  </div>
</div>
  <input id="calendar-start-date" type="hidden" value="{{ start_date }}"/>
  <input id="calendar-end-date" type="hidden" value="{{ end_date }}"/>
<div id="calendar-container">
  <div id="calendar"></div>
</div>
<button id = "data-load" onclick="sendAllEvents('{{pass_key}}','{{pid}}')">제출하기</button>
<!-- <input type = "submit" value = "프로젝트 공유하기"></input> -->

</body>
</html>

newplanin/master_calendar/templates/master_calendar/thankyou.html
{% extends "loginbase.html"%}
{% load static %}

{% block title %}
thankyou
{% endblock %}

{% block head %}
{% endblock %}

{%block body%}
    <div class = "container-box"> 
        <div> 
            <h1>일정 제출이 완료되었습니다.</h1>
            <p> 포지션에 참여하는 모든 면접관들의 캘린더를 입력을 기다리고 있어요.</p>
            <p> 완료가 되면 메일로 모두가 가능한 시간을 전달드립니다</p>
        </div>
        <div id= "more-info"> 
            <p>면접일정 조정 캘린더, 플래닌을 더 알아보세요!</p>
            <div>
            <button type="button" onclick="location.href=`{% url 'login:login' %}`">더 알아보기</button>
            </div>
        </div> 
    </div>
{%endblock%}