newplanin/home/urls.py
from django.urls import path 
from . import views


app_name = "home"

urlpatterns = [
    path('', views.load_project_lists, name = "home"),
    path('create-project/', views.create_project, name="create"),
    path('edit-project/<str:pid>/',views.edit_project, name="edit"),
    path('delete-project/<str:pid>/',views.delete_project, name="delete")
    # path('invite/<int:pid>/<str:user_email>',views.invite_users, name="invite_users")
]

newplanin/login/urls.py
from django.urls import path 
from . import views


app_name = "login"

urlpatterns = [
    path('', views.login, name ='login'),
    path('logout/', views.logout, name ='logout'),
   
]

newplanin/newplanin/urls.py
import re
from django.contrib import admin
from django.urls import path , include
from django.shortcuts import redirect
from django.urls import reverse
from datetime import datetime
from django.http import JsonResponse
from login import views
# def google_login(request) :
#     return redirect(reverse(login:))
def social_login_cancel(request) :
    return redirect(reverse("boot:login") + "?error=cancelled")

def social_login_error(request) :
    return redirect(reverse("boot:login") + "?error=error")

# def google_login(reqeust) :
#     return redirect(reverse('https://accounts.google.com/o/oauth2/auth/oauthchooseaccount')+"?client_id=")


def test_timezone(request):
    print(request.GET.get("time"))
    print(datetime.now())
    return JsonResponse({
        "now": str(datetime.now())
    })


urlpatterns = [
    path("test-time/", test_timezone),
    # path("accounts/google/login/",google_login),
    path("accounts/social/login/cancelled",social_login_cancel),
    path("accounts/social/login/error", social_login_error),
    path('accounts/',include('allauth.urls')),

    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('',views.login),
    path('home/', include('home.urls')),
    path('calendar/',include('master_calendar.urls')),
    

]

newplanin/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com"> 
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
  <link rel="stylesheet" href="{% static 'home/css/base.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
  <title>{% block title %}Title{% endblock %}</title>
  

  {% block head %}
  {% endblock %}

</head>
<body>
    <nav class="nav">
        <div class="nav-link active">
            <a href="{% url 'home:home' %}">대시보드</a>
        </div>
        <div class="nav-link">
            <a href="{% url 'home:create' %}">포지션 생성</a>
        </div>
        <div class="nav nav-pills">
        <form action="{% url 'login:logout' %}" method = "post">
            {% csrf_token %}
                <button class = "button-logout" type="submit">로그아웃</button>
            </form>
        </div>
    </nav>

    {% block body %}
    {% endblock %}
</body>
</html>

newplanin/templates/loginbase.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com"> 
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
  <link rel="stylesheet" href="{% static 'home/css/base.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
  <title>{% block title %}Title{% endblock %}</title>
  

  {% block head %}
  {% endblock %}

    {% block body %}
    {% endblock %}
</body>
</html>